"""Download hourly candles and funding-rate history for the OPUS LUMEN universe.

Usage:  python tools/fetch_data.py [--hours 4320]
Writes: dist/data/market.js  (an ES module the app and the tests import)

Sources: Binance public market data (spot klines) and Binance USD-M futures
funding history. Standard library only, no API key.
"""
import argparse, json, time, urllib.request
from pathlib import Path

ASSETS = {  # asset: (spot symbol, perp symbol, perp price multiplier)
    "SOL": ("SOLUSDT", "SOLUSDT"),
    "BTC": ("BTCUSDT", "BTCUSDT"),
    "ETH": ("ETHUSDT", "ETHUSDT"),
    "JUP": ("JUPUSDT", "JUPUSDT"),
    "BONK": ("BONKUSDT", "1000BONKUSDT"),
    "WIF": ("WIFUSDT", "WIFUSDT"),
    "JTO": ("JTOUSDT", "JTOUSDT"),
    "PYTH": ("PYTHUSDT", "PYTHUSDT"),
}
SPOT = ["https://api.binance.com", "https://data-api.binance.vision"]
FUT = ["https://fapi.binance.com"]
OUT = Path(__file__).resolve().parent.parent / "dist" / "data" / "market.js"


def get(hosts, path):
    last = None
    for host in hosts:
        for _ in range(3):
            try:
                with urllib.request.urlopen(host + path, timeout=12) as r:
                    return json.load(r)
            except Exception as e:  # retry, then try the next host
                last = e
                time.sleep(1)
    raise SystemExit(f"could not fetch {path}: {last}")


def candles(symbol, hours):
    rows, end = [], None
    while len(rows) < hours:
        q = f"/api/v3/klines?symbol={symbol}&interval=1h&limit=1000" + (f"&endTime={end}" if end else "")
        batch = get(SPOT, q)
        if not batch:
            break
        rows = batch + rows
        end = batch[0][0] - 1
        time.sleep(0.15)
    rows = [r for r in rows if r[6] < time.time() * 1000][-hours:]  # closed candles only
    return [[r[0] // 1000, float(r[1]), float(r[2]), float(r[3]), float(r[4]), round(float(r[7]))] for r in rows]


def funding(symbol, since_ms):
    out, start = [], since_ms
    while True:
        batch = get(FUT, f"/fapi/v1/fundingRate?symbol={symbol}&startTime={start}&limit=1000")
        if not batch:
            break
        out += [[b["fundingTime"] // 1000, float(b["fundingRate"])] for b in batch]
        if len(batch) < 1000:
            break
        start = batch[-1]["fundingTime"] + 1
        time.sleep(0.15)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hours", type=int, default=4320)
    a = ap.parse_args()
    data, first, last = {}, None, None
    for asset, (spot, perp) in ASSETS.items():
        c = candles(spot, a.hours)
        f = funding(perp, (c[0][0] - 40 * 86400) * 1000)
        data[asset] = {"candles": c, "funding": f}
        first = c[0][0] if first is None else max(first, c[0][0])
        last = c[-1][0] if last is None else min(last, c[-1][0])
        print(f"{asset:5s} {len(c)} candles, {len(f)} funding prints", flush=True)
    # align every asset to the same hourly window
    for v in data.values():
        v["candles"] = [r for r in v["candles"] if first <= r[0] <= last]
    n = {k: len(v["candles"]) for k, v in data.items()}
    assert len(set(n.values())) == 1, f"misaligned candles: {n}"
    meta = {"source": "Binance spot klines 1h (quote volume) + USD-M funding history", "assets": list(ASSETS),
            "from": first, "to": last, "hours": next(iter(n.values()))}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(f'"{k}": {json.dumps(v, separators=(",", ":"))}' for k, v in data.items())
    OUT.write_text("// Generated by tools/fetch_data.py. candles: [unixSec, open, high, low, close, quoteVolume]; funding: [unixSec, rate]\n"
                   f"export const META = {json.dumps(meta)};\nexport const MARKET = {{\n{body}\n}};\n", encoding="utf-8")
    print("wrote", OUT, f"{OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
